baseurl = "https://ameyathakur.com/"
theme = "smol"
builddrafts = true
canonifyurls = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Ameya Thakur"
title = "Ameya Thakur"
pluralizelisttitles = false

[permalinks]
    blog = "blog/:slug/"

# Parameters
[params]
    subtitle = "My blog/projects/portfolio"
    dateFmt = "Jan 01, 2006"
    mainSections = "blog"


[menu]
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
        weight = 2

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3

    [[menu.footer]]
        name = "Github"
        url = "https://github.com/indiandennis"
        weight = 1

    [[menu.footer]]
        name = "Email"
        url = "mailto:website@ameyathakur.com"
        weight = 2
