baseurl = "/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Ameya Thakur"
title = ""
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "My blog"
copyright = "Copyright © 2019 Ameya Thakur"
logofile = "img/logo.png"
faviconfile = "favicon.ico"
highlightjs = true
progressively = false
align_left = false
lang = "en"
github = "indiandennis"
email = "website@ameyathakur.com"
linkedin = "ameyanthakur"
twitter = ""
social_banner = ""
posts_navigation = true
small_banner_logo = true
