--- 
backend: 
  branch: master
  name: git-gateway
site_url: https://ameyathakur.com
display_url: https://ameyathakur.com
collections: 
  - 
    create: true
    fields: 
      - 
        label: Title
        name: title
        widget: string
      - 
        format: YYYY-MM-DD
        label: Date
        name: date
        widget: date
      - 
        label: Tags
        name: tags
        required: false
        widget: list
      - 
        label: Body
        name: body
        required: false
        widget: markdown
    folder: content/blog
    label: Blog
    name: blog
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
  - 
    create: true
    fields: 
      - 
        label: Title
        name: title
        widget: string
      - 
        label: Description
        name: description
        widget: string
      - 
        format: YYYY-MM-DD
        label: Date
        name: date
        required: false
        widget: date
      - 
        label: Tags
        name: tags
        required: false
        widget: list
      - 
        label: Body
        name: body
        required: false
        widget: markdown
    folder: content/projects
    label: Projects
    name: projects
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
  - 
    files: 
      - 
        fields: 
          - 
            label: Title
            name: title
            widget: string
          - 
            label: Body
            name: body
            required: false
            widget: markdown
        file: content/about.md
        label: "About Page"
        name: about
      - 
        fields: 
          - 
            label: Title
            name: title
            widget: string
          - 
            label: Body
            name: body
            required: false
            widget: markdown
        file: content/home.md
        label: "Home Page"
        name: home
      - 
        fields: 
          - 
            label: Body
            name: body
            required: false
            widget: markdown
        file: content/license.md
        label: "License"
        name: license
    label: Pages
    name: pages
media_folder: static/img/uploads
public_folder: /img/uploads
publish_mode: editorial_workflow
